local Modules = mUI:NewModule("mUI.Modules.General.Modules")

function Modules:OnInitialize()
    -- Modules
    self.Theme = mUI:GetModule("mUI.Modules.General.Theme")
    self.Font = mUI:GetModule("mUI.Modules.General.Font")
    self.Repair = mUI:GetModule("mUI.Modules.General.Repair")
    self.Sell = mUI:GetModule("mUI.Modules.General.Sell")
    self.Delete = mUI:GetModule("mUI.Modules.General.Delete")
    self.Duel = mUI:GetModule("mUI.Modules.General.Duel")
    self.Release = mUI:GetModule("mUI.Modules.General.Release")
    self.Resurrection = mUI:GetModule("mUI.Modules.General.Resurrection")
    self.Invite = mUI:GetModule("mUI.Modules.General.Invite")
    self.Cinematic = mUI:GetModule("mUI.Modules.General.Cinematic")
    self.TalkingHead = mUI:GetModule("mUI.Modules.General.TalkingHead")
    self.ItemInfo = mUI:GetModule("mUI.Modules.General.ItemInfo")
    self.Stats = mUI:GetModule("mUI.Modules.General.Stats")
    self.MovementSpeed = mUI:GetModule("mUI.Modules.General.MovementSpeed")
    self.ErrorMessages = mUI:GetModule("mUI.Modules.General.ErrorMessages")
    self.Friendlist = mUI:GetModule("mUI.Modules.General.Friendlist")
end

function Modules:OnEnable()
    -- Enable Modules
    self.Theme:Enable()
    self.Font:Enable()
    self.Repair:Enable()
    self.Sell:Enable()
    self.Delete:Enable()
    self.Duel:Enable()
    self.Release:Enable()
    self.Resurrection:Enable()
    self.Invite:Enable()
    self.Cinematic:Enable()
    self.TalkingHead:Enable()
    self.ItemInfo:Enable()
    self.Stats:Enable()
    self.MovementSpeed:Enable()
    self.ErrorMessages:Enable()
    self.Friendlist:Enable()
end

function Modules:OnDisable()
    -- Disable Modules
    self.Theme:Disable()
    self.Font:Disable()
    self.Repair:Disable()
    self.Sell:Disable()
    self.Delete:Disable()
    self.Duel:Disable()
    self.Release:Disable()
    self.Resurrection:Disable()
    self.Invite:Disable()
    self.Cinematic:Disable()
    self.TalkingHead:Disable()
    self.ItemInfo:Disable()
    self.Stats:Disable()
    self.MovementSpeed:Disable()
    self.ErrorMessages:Disable()
    self.Friendlist:Disable()
end
